### ISSUE TITLE
Is ROLIE the right example to use in this draft?

### ISSUE THREAD

**Issue by adammontville** [adammontville/draft-mandm-sacm-architecture-redux#1]
In Section 4 "A Word On SACM Components, Capabilities, and Interfaces" we use ROLIE as an example. Are there other examples we could use? Is ROLIE sufficient?

**Comment by wmunyan** [comment]
I wonder if there could be some sub-sections in there to give a notional example for each area, such as policy, collection, and evaluation...  So ROLIE, maybe YANG, maybe CIS-CAT?

**Comment by adammontville** [comment]
What would that structure look like? Are you thinking something like this:

# A Word On SACM Components, Capabilities, and Interfaces
(Keep introductory text here)
## Policy Services
(Move ROLIE text here)
## ECP/SWIMA
(Add software inventory information here)
## Datastream
(Add the configuration assessment case here, i.e. CIS-CAT)
## YANG Push
(Add network device configuration assessment information here)

We could certainly do that.

**Comment by adammontville** [comment]
Spoke to Bill about this. Good to go with the example. Slightly modified subheadings, but the idea remains unchanged.
